require: rubocop-rails

AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - "**/vendor/**/*"
    - "bin/*"
    - "db/schema.rb"

Rails:
  Enabled: true

# Increase the default Rubocop length limitations.
# In many cases the default limits are too strict for any nontrivial functionality.
# Following the limits can end up splitting even relatively simple functionality
# into many functions/methods which can hurt readability instead of increasing it.

Metrics/ClassLength:
  Max: 100

Metrics/BlockLength:
  Max: 50
  Exclude:
    - "spec/**/*.rb"
    - "config/environments/*.rb"

Metrics/MethodLength:
  Max: 50

Metrics/PerceivedComplexity:
  Max: 10

Metrics/CyclomaticComplexity:
  Max: 10

Layout/LineLength:
  Max: 100
  Exclude:
    - config/environments/*.rb

Style/BlockComments:
  Enabled: false

Style/CommentedKeyword:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Style/ClassAndModuleChildren:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
